version: '2'

services:
  frontend:
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    ports:
      - '8080:8080'
  nginx:
    restart: always
    build: ./compose/nginx
    ports:
      - "80:80"
      - "443:443"