version: '2'

services:
  frontend:
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    ports:
      - '8080:8080'
    command: serve -s -p 8080 build
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"